### ISSUE TITLE
Improve custom endpoint documentation

### ISSUE THREAD

**Issue by teunmooij** [teunmooij/payload-tools#25]
Waiting for reply from payload about extending the config.

**Comment by thnhat51202574** [comment]
Thank you, @teunmooij , for the excellent plugin for Payload CMS. I encountered an issue related to the custom endpoint. I want to add an API with type='options' to my custom endpoint. However, when I do so, the Swagger document removes all the existing endpoints with types 'get,' 'post,' and 'delete.' 
My concern is whether there is a solution to merge the default types 
![Screenshot 2023-05-22 at 13 20 36](https://github.com/teunmooij/payload-tools/assets/17866682/70c77d50-69d9-43b7-9d18-998fe1378d68)
with the custom type in our Swagger document.

**Comment by teunmooij** [comment]
> Thank you, @teunmooij , for the excellent plugin for Payload CMS. I encountered an issue related to the custom endpoint. I want to add an API with `type='options'` to my custom endpoint. However, when I do so, the Swagger document removes all the existing endpoints with types `'get,' 'post,' and 'delete'` My concern is whether there is a solution to merge the default types with the custom type in our Swagger document. ![Screenshot 2023-05-22 at 13 20 36](https://user-images.githubusercontent.com/17866682/239818951-70c77d50-69d9-43b7-9d18-998fe1378d68.png)

I've created [a separate issue](https://github.com/teunmooij/payload-tools/issues/62) to look into this problem.
