### ISSUE TITLE
[Feature request]: Support collection access endpoint

### ISSUE THREAD

**Issue by thnhat51202574** [teunmooij/payload-tools#61]
### Package name

payload-openapi

### Description

We don't have any access endpoint for the collection level yet

**Comment by teunmooij** [comment]
I'm not aware of any such endpoint. As far as I know there's only the global `/access` endpoint.
Can you point me to the documentation of this endpoint?

**Comment by thnhat51202574** [comment]
I couldn't find any documentation about the collections endpoint. However, along with the global `/access` endpoint, the admin UI refers to the collection as `<slug>/access/:id` when checking permissions for accessing the detail page
![Screenshot 2023-05-23 at 18 41 52](https://github.com/teunmooij/payload-tools/assets/17866682/7938cc8f-f7c0-4eb6-8bdc-0a68f7049006)

**Comment by teunmooij** [comment]
Thanks for the update. I'll look into it.

**Comment by thnhat51202574** [comment]
Hi @teunmooij , do we have any solutions for adding Swagger options to all the collection endpoints?

**Comment by teunmooij** [comment]
This is not a documented feature of payload. Therefore it's uncertain whether it will be supported in future versions. I will not add this. If you want to have this documented on your payload instance, please use one of the extension options described in the docs.
