### ISSUE TITLE
Loosing existing endpoint when merging custom method

### ISSUE THREAD

**Issue by teunmooij** [teunmooij/payload-tools#62]
Thank you, @teunmooij , for the excellent plugin for Payload CMS. I encountered an issue related to the custom endpoint. I want to add an API with `type='options'` to my custom endpoint. However, when I do so, the Swagger document removes all the existing endpoints with types `'get,' 'post,' and 'delete'` 
My concern is whether there is a solution to merge the default types with the custom type in our Swagger document.
![Screenshot 2023-05-22 at 13 20 36](https://github.com/teunmooij/payload-tools/assets/17866682/70c77d50-69d9-43b7-9d18-998fe1378d68)

_Originally posted by @thnhat51202574 in https://github.com/teunmooij/payload-tools/issues/25#issuecomment-1556606045_

**Comment by teunmooij** [comment]
@thnhat51202574 thanks for reporting this potential bug. Can you maybe explain how you added the custom endpoint?

I tried to reproduce, but had no issue adding the endpoint
![image](https://github.com/teunmooij/payload-tools/assets/1759878/a6edefc3-bbcb-4288-8d10-ad0c47adf972)

**Comment by teunmooij** [comment]
Your configuration is correct. I was able to reproduce. Thanks for the extra info.
I'll write a fix.

**Comment by teunmooij** [comment]
I've released version 1.1.3, which fixes this issue.

The issue on which you originally posted this issue intends to improve custom endpoint documentation in general (eg make it possible to specify a return type). I'll pick that one up soon.

**Comment by thnhat51202574** [comment]
Thanks a lot @teunmooij
