### ISSUE TITLE
[Bug]: `payload-swagger@1.0.5` is incompatible with `payload@1.9.0`+

### ISSUE THREAD

**Issue by klapec** [teunmooij/payload-tools#65]
### Package name

payload-swagger

### What happened?

I'm getting

```
@xxx/cms:dev: TypeError: Cannot read properties of undefined (reading 'set')
@xxx/cms:dev:     at /Volumes/dev/repos/xxx/node_modules/.pnpm/payload@1.9.1_@types+react@18.0.28_esbuild@0.16.3_typescript@5.0.4/node_modules/payload/src/utilities/entityToJSONSchema.ts:326:33
@xxx/cms:dev:     at Array.reduce (<anonymous>)
@xxx/cms:dev:     at entityFieldsToJSONSchema (/Volumes/dev/repos/xxx/node_modules/.pnpm/payload@1.9.1_@types+react@18.0.28_esbuild@0.16.3_typescript@5.0.4/node_modules/payload/src/utilities/entityToJSONSchema.ts:56:43)
@xxx/cms:dev:     at /Volumes/dev/repos/xxx/node_modules/.pnpm/payload@1.9.1_@types+react@18.0.28_esbuild@0.16.3_typescript@5.0.4/node_modules/payload/src/utilities/entityToJSONSchema.ts:321:18
@xxx/cms:dev:     at Array.reduce (<anonymous>)
@xxx/cms:dev:     at entityFieldsToJSONSchema (/Volumes/dev/repos/xxx/node_modules/.pnpm/payload@1.9.1_@types+react@18.0.28_esbuild@0.16.3_typescript@5.0.4/node_modules/payload/src/utilities/entityToJSONSchema.ts:56:43)
@xxx/cms:dev:     at entityToJSONSchema (/Volumes/dev/repos/xxx/node_modules/.pnpm/payload@1.9.1_@types+react@18.0.28_esbuild@0.16.3_typescript@5.0.4/node_modules/payload/src/utilities/entityToJSONSchema.ts:439:8)
@xxx/cms:dev:     at /Volumes/dev/repos/xxx/node_modules/.pnpm/payload-openapi@1.1.3_payload@1.9.1/node_modules/payload-openapi/dist/schemas/entity-to-schema.js:41:59
@xxx/cms:dev:     at Generator.next (<anonymous>)
@xxx/cms:dev:     at /Volumes/dev/repos/xxx/node_modules/.pnpm/payload-openapi@1.1.3_payload@1.9.1/node_modules/payload-openapi/dist/schemas/entity-to-schema.js:8:71
```
after updating payload to 1.9.1 (latest as of writing this bug report).
Apparently you're calling payload's [`entityToJSONSchema`](https://github.com/teunmooij/payload-tools/blob/d146f17f5e1cb42c372ea8cd0afbced2d15b63fc/packages/openapi/src/schemas/entity-to-schema.ts#L50) without passing down the third required parameter - [`fieldDefinitionsMap`](https://github.com/payloadcms/payload/blob/8fe3e59e7610db2f9a6127c579a3e5e19f959afb/src/utilities/entityToJSONSchema.ts#L46).

### Setps to reproduce

- install `payload-swagger@1.0.5`
- install `payload@1.9.0`
- add `interfaceName` to a field configuration
- 💥

### Tool version

1.0.5

### Payload version

1.9.1

**Comment by teunmooij** [comment]
Payload openapi uses payloads `entityToJSONSchema`, which is also used to generate the typescript definitions, to generate parts of the openapi document. This function is part of payloads public interface.
- In payload 1.9 a breaking change was made to this function by adding a required 3rd parameter
- In payload 1.10 another breaking change was made by removing it from the public api.
I'm looking into best ways to solve both issues in a way that it will work with all versions op payload.

**Comment by teunmooij** [comment]
I've published a new version of `payload-swagger` and `payload-openapi` that fixes this bug.

However, payload version 1.9.3 - 1.10.1 contain a bug. Openapi documentation will not work with those version. The next version of payload contains the fix for that bug, but has not yet been published.

**Comment by thnhat51202574** [comment]
Hi @teunmooij, the payload tool has deployed a new version 1.10.2, which includes a [fix](https://github.com/payloadcms/payload/releases/tag/v1.10.2). I'm wondering if this version is compatible with the latest version of payloadtools?

**Comment by teunmooij** [comment]
I haven't tested this version yet, but yes, it should be.

**Comment by teunmooij** [comment]
Tested. It works

**Comment by klapec** [comment]
Can confirm, everything works fine. Thanks!
